// <auto-generated />
using System;
using GlobalSolution.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GlobalSolution.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlobalSolution.Models.Alerta", b =>
                {
                    b.Property<long>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAlerta"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<long>("IdLeitura")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LEITURA");

                    b.Property<long>("IdPlantacao")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PLANTACAO");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DS_MENSAGEM");

                    b.Property<string>("Severidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("DS_SEVERIDADE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("DS_STATUS");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_ALERTA");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdLeitura");

                    b.HasIndex("IdPlantacao");

                    b.ToTable("TB_ALERTA");
                });

            modelBuilder.Entity("GlobalSolution.Models.Leitura", b =>
                {
                    b.Property<long>("IdLeitura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LEITURA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdLeitura"));

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_LEITURA");

                    b.Property<long>("IdSensor")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_SENSOR");

                    b.Property<decimal?>("Ndvi")
                        .HasColumnType("FLOAT")
                        .HasColumnName("NR_NDVI");

                    b.Property<decimal?>("Precipitacao")
                        .HasColumnType("FLOAT")
                        .HasColumnName("NR_PRECIPITACAO");

                    b.Property<decimal?>("Temperatura")
                        .HasColumnType("FLOAT")
                        .HasColumnName("NR_TEMPERATURA");

                    b.Property<decimal?>("Umidade")
                        .HasColumnType("FLOAT")
                        .HasColumnName("NR_UMIDADE");

                    b.HasKey("IdLeitura");

                    b.HasIndex("IdSensor");

                    b.ToTable("TB_LEITURA");
                });

            modelBuilder.Entity("GlobalSolution.Models.Localizacao", b =>
                {
                    b.Property<long>("IdLocalizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LOCALIZACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdLocalizacao"));

                    b.Property<string>("Cep")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NR_CEP");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_CIDADE");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("SG_ESTADO");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("FLOAT")
                        .HasColumnName("NR_LATITUDE");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("FLOAT")
                        .HasColumnName("NR_LONGITUDE");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NM_PAIS");

                    b.HasKey("IdLocalizacao");

                    b.ToTable("TB_LOCALIZACAO");
                });

            modelBuilder.Entity("GlobalSolution.Models.Plantacao", b =>
                {
                    b.Property<long>("IdPlantacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PLANTACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPlantacao"));

                    b.Property<decimal>("AreaHectares")
                        .HasColumnType("FLOAT")
                        .HasColumnName("NR_AREA_HECTARES");

                    b.Property<string>("Cultura")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("DS_CULTURA");

                    b.Property<long>("IdPropriedade")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PROPRIEDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_PLANTACAO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("DS_STATUS");

                    b.HasKey("IdPlantacao");

                    b.HasIndex("IdPropriedade");

                    b.ToTable("TB_PLANTACAO");
                });

            modelBuilder.Entity("GlobalSolution.Models.Propriedade", b =>
                {
                    b.Property<long>("IdPropriedade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PROPRIEDADE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPropriedade"));

                    b.Property<decimal>("AreaTotal")
                        .HasColumnType("FLOAT")
                        .HasColumnName("NR_AREA_TOTAL");

                    b.Property<long>("IdLocalizacao")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LOCALIZACAO");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_PROPRIEDADE");

                    b.Property<string>("TipoSolo")
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("TP_SOLO");

                    b.HasKey("IdPropriedade");

                    b.HasIndex("IdLocalizacao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TB_PROPRIEDADE");
                });

            modelBuilder.Entity("GlobalSolution.Models.Sensor", b =>
                {
                    b.Property<long>("IdSensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_SENSOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSensor"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ST_ATIVO");

                    b.Property<DateTime>("DataInstalacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_INSTALACAO");

                    b.Property<long>("IdPlantacao")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PLANTACAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_SENSOR");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_SENSOR");

                    b.HasKey("IdSensor");

                    b.HasIndex("IdPlantacao");

                    b.ToTable("TB_SENSOR");
                });

            modelBuilder.Entity("GlobalSolution.Models.Usuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUsuario"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ST_ATIVO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_USUARIO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DS_SENHA");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TB_USUARIO");
                });

            modelBuilder.Entity("GlobalSolution.Models.Alerta", b =>
                {
                    b.HasOne("GlobalSolution.Models.Leitura", "Leitura")
                        .WithMany("Alertas")
                        .HasForeignKey("IdLeitura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlobalSolution.Models.Plantacao", "Plantacao")
                        .WithMany("Alertas")
                        .HasForeignKey("IdPlantacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Leitura");

                    b.Navigation("Plantacao");
                });

            modelBuilder.Entity("GlobalSolution.Models.Leitura", b =>
                {
                    b.HasOne("GlobalSolution.Models.Sensor", "Sensor")
                        .WithMany("Leituras")
                        .HasForeignKey("IdSensor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("GlobalSolution.Models.Plantacao", b =>
                {
                    b.HasOne("GlobalSolution.Models.Propriedade", "Propriedade")
                        .WithMany("Plantacoes")
                        .HasForeignKey("IdPropriedade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("GlobalSolution.Models.Propriedade", b =>
                {
                    b.HasOne("GlobalSolution.Models.Localizacao", "Localizacao")
                        .WithMany("Propriedades")
                        .HasForeignKey("IdLocalizacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlobalSolution.Models.Usuario", "Usuario")
                        .WithMany("Propriedades")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Localizacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GlobalSolution.Models.Sensor", b =>
                {
                    b.HasOne("GlobalSolution.Models.Plantacao", "Plantacao")
                        .WithMany("Sensores")
                        .HasForeignKey("IdPlantacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plantacao");
                });

            modelBuilder.Entity("GlobalSolution.Models.Leitura", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("GlobalSolution.Models.Localizacao", b =>
                {
                    b.Navigation("Propriedades");
                });

            modelBuilder.Entity("GlobalSolution.Models.Plantacao", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("GlobalSolution.Models.Propriedade", b =>
                {
                    b.Navigation("Plantacoes");
                });

            modelBuilder.Entity("GlobalSolution.Models.Sensor", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("GlobalSolution.Models.Usuario", b =>
                {
                    b.Navigation("Propriedades");
                });
#pragma warning restore 612, 618
        }
    }
}
